POST http://localhost:3002/cadastro
Content-Type: application/json

{
    "email":
    "username": 
    "senha":
}

###

POST http://localhost:3002/login
Content-Type: application/json

{
    "username":
    "senha":
}

###

GET http://localhost:3002/bookhub?search=conrad

###

PUT http://localhost:3002/atualizacao/
Content-Type: application/json

{
    "username": 
    "senha":
}

###

DELETE http://localhost:3002/exclusao/